[workspace]
authors = ["Victor-Iroko <irokovictor7@gmail.com>"]
channels = ["conda-forge"]
name = "training"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = "<2"
pandas = ">=2.3.3,<3"
lightfm = ">=1.17,<2"
scikit-learn = ">=1.8.0,<2"
seaborn = ">=0.13.2,<0.14"
psycopg2 = ">=2.9.11,<3"
python-dotenv = ">=1.2.1,<2"
scipy = ">=1.17.0,<2"
joblib = ">=1.5.3,<2"
ipykernel = ">=7.1.0,<8"
huggingface_hub = ">=0.26.0"
